 // lib/allPhones.ts
// ✅ SINGLE SOURCE OF TRUTH — Home page + Detail page dono yahan se data lete hain

export interface Phone {
  id: number;
  name: string;
  price: number;
  image: string;
  brand: string;
  priceType?: 'Official' | 'Exp' | 'PTA Approved';
  variants?: { label: string; price: number }[];
  highlights?: { label: string; value: string }[];
  specs?: Record<string, Record<string, string>>;
}

export const ALL_PHONES: Phone[] = [

  // ── REALME ─────────────────────────────────────────────────
  {
    id: 1,
    name: 'Realme C85 Pro',
    price: 59999,
    image: '/mobiles/realme-c85-pro.png',
    brand: 'Realme',
    priceType: 'Official',
    variants: [{ label: '8GB + 128GB', price: 59999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'Realme UI 5.0', SIM: 'Dual Nano-SIM', Weight: '195 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '16 MP' },
      Memory:       { RAM: '8 GB', ROM: '128 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '45W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.67"', Resolution: '1080 x 2400', Extras: '120Hz' },
      Processor:    { Chipset: 'Snapdragon 695 (6nm)', CPU: 'Octa-core', GPU: 'Adreno 619' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 a/b/g/n/ac', Bluetooth: 'v5.1', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 2,
    name: 'Infinix Hot 60 Pro Plus',
    price: 59999,
    image: '/mobiles/infinix-hot-60-pro-plus.png',
    brand: 'Infinix',
    priceType: 'Official',
    variants: [{ label: '8GB + 256GB', price: 59999 }],
    specs: {
      Build:        { OS: 'Android 15', UI: 'XOS 15.1', SIM: 'Dual Nano-SIM', Weight: '185 g' },
      Camera:       { Back: '64 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '16 MP' },
      Memory:       { RAM: '8 GB', ROM: '256 GB', Card: 'MicroSDXC' },
      Battery:      { Capacity: '5200 mAh', Charging: '45W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.78"', Resolution: '1080 x 2400', Extras: '144Hz' },
      Processor:    { Chipset: 'Mediatek Helio G200 (6nm)', CPU: 'Octa-core', GPU: 'Mali-G57 MC2' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 a/b/g/n/ac', Bluetooth: 'v5.4', USB: 'USB Type-C 2.0', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Under display (optical)', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers (JBL)', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 3,
    name: 'Realme Note 70',
    price: 31999,
    image: '/mobiles/realme-note-70.png',
    brand: 'Realme',
    priceType: 'Official',
    variants: [{ label: '6GB + 128GB', price: 31999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'Realme UI 5.0', SIM: 'Dual Nano-SIM', Weight: '188 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '6 GB', ROM: '128 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '33W Fast Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.67"', Resolution: '1080 x 2400', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc T612 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G57' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 4,
    name: 'Infinix Hot 60 Pro',
    price: 46999,
    image: '/mobiles/infinix-hot-60-pro.png',
    brand: 'Infinix',
    priceType: 'Official',
    variants: [{ label: '8GB + 128GB', price: 46999 }],
    specs: {
      Build:        { OS: 'Android 15', UI: 'XOS 15.1', Dimensions: '163.5 x 75.9 x 6.6 mm', Weight: '170 g', SIM: 'Nano-SIM + Nano-SIM', Colors: 'Sleek Black, Titanium Silver, Coral Tides, Sapphire Blue, Jungle Breath, Orange Rose Valley', Material: 'Glass front + Gorilla Glass 7i, Plastic back, Plastic frame' },
      Camera:       { Back: '50 MP, f/1.6, 27mm (wide), 1/2.8", PDAF, Dual LED Flash', 'Back Features': 'HDR, Panorama', 'Back Video': '1440p@30fps, 1080p@30/60fps', Front: '13 MP', 'Front Features': '1440p@30fps, 1080p@30/60fps' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Memory:       { RAM: '8 GB', ROM: '128 GB', Card: 'MicroSDXC (Dedicated Slot)' },
      Battery:      { Capacity: '5160 mAh', Type: 'Si/C Li-Ion', Charging: '45W wired, 50% in 22 min, 10W reverse wired' },
      Display:      { Technology: 'AMOLED Capacitive Touchscreen', Size: '6.78 Inches', Resolution: '1224 x 2720 Pixels', 'Pixel Density': '440 PPI', Protection: 'Corning Gorilla Glass 7i', Extras: '144Hz, 2160Hz PWM, 700 nits (typ), 1600 nits (HBM), 4500 nits (peak)' },
      Processor:    { CPU: 'Octa-core (2 x 2.2 GHz Cortex-A76 + 6 x 2.0 GHz Cortex-A55)', Chipset: 'Mediatek Helio G200 (6 nm)', GPU: 'Mali-G57 MC2 (1.1GHz)' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 a/b/g/n/ac, dual-band', Bluetooth: 'v5.4 with A2DP, LE', GPS: 'Yes + A-GPS support', USB: 'USB Type-C 2.0', OTG: 'Yes', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Yes (Under display, optical)', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Compass, Gyro, Proximity' },
      Sound:        { Speaker: 'Tuned by JBL, 24-bit/192kHz Hi-Res audio, Speaker Phone' },
    },
  },
  {
    id: 5,
    name: 'Infinix Hot 60i',
    price: 33999,
    image: '/mobiles/infinix-hot-60i.png',
    brand: 'Infinix',
    priceType: 'Official',
    variants: [{ label: '4GB + 64GB', price: 33999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'XOS 14', SIM: 'Dual Nano-SIM', Weight: '192 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '4 GB', ROM: '64 GB', Card: 'MicroSDXC' },
      Battery:      { Capacity: '5000 mAh', Charging: '18W Fast Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.6"', Resolution: '720 x 1612', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc T606 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G57' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 6,
    name: 'Realme C71',
    price: 36999,
    image: '/mobiles/realme-c71.png',
    brand: 'Realme',
    priceType: 'Official',
    variants: [{ label: '6GB + 128GB', price: 36999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'Realme UI 5.0', SIM: 'Dual Nano-SIM', Weight: '190 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '6 GB', ROM: '128 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '33W Fast Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.67"', Resolution: '720 x 1604', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc T612 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G57' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 7,
    name: 'Tecno Camon 40 Premier 5G',
    price: 89999,
    image: '/mobiles/tecno-camon-40-premier-5g.png',
    brand: 'Tecno',
    priceType: 'Official',
    variants: [{ label: '12GB + 256GB', price: 89999 }],
    specs: {
      Build:        { OS: 'Android 15', UI: 'HiOS 15', SIM: 'Dual Nano-SIM', Weight: '198 g' },
      Camera:       { Back: '50 MP + 50 MP + 8 MP', 'Back Video': '4K@30fps', Front: '50 MP' },
      Memory:       { RAM: '12 GB', ROM: '256 GB', Card: 'No' },
      Battery:      { Capacity: '5200 mAh', Charging: '70W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.78"', Resolution: '1080 x 2436', Extras: '144Hz, 5000 nits peak' },
      Processor:    { Chipset: 'Dimensity 8200 (4nm)', CPU: 'Octa-core', GPU: 'Mali-G610' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 6E', Bluetooth: 'v5.3', USB: 'USB Type-C 2.0', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Under display (optical)', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Compass, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 8,
    name: 'Tecno Camon 40 Pro',
    price: 74999,
    image: '/mobiles/tecno-camon-40-pro.png',
    brand: 'Tecno',
    priceType: 'Official',
    variants: [{ label: '8GB + 256GB', price: 74999 }],
    specs: {
      Build:        { OS: 'Android 15', UI: 'HiOS 15', SIM: 'Dual Nano-SIM', Weight: '193 g' },
      Camera:       { Back: '50 MP + 50 MP', 'Back Video': '4K@30fps', Front: '50 MP' },
      Memory:       { RAM: '8 GB', ROM: '256 GB', Card: 'No' },
      Battery:      { Capacity: '5000 mAh', Charging: '45W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.67"', Resolution: '1080 x 2400', Extras: '120Hz' },
      Processor:    { Chipset: 'Dimensity 7300 (4nm)', CPU: 'Octa-core', GPU: 'Mali-G615' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 6', Bluetooth: 'v5.3', USB: 'USB Type-C', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Under display (optical)', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 9,
    name: 'Infinix Note 50 Pro Plus',
    price: 64999,
    image: '/mobiles/infinix-note-50-pro-plus.png',
    brand: 'Infinix',
    priceType: 'Official',
    variants: [{ label: '12GB + 256GB', price: 64999 }],
    specs: {
      Build:        { OS: 'Android 15', UI: 'XOS 15.1', SIM: 'Dual Nano-SIM', Weight: '205 g' },
      Camera:       { Back: '108 MP + 8 MP + 2 MP', 'Back Video': '4K@30fps', Front: '32 MP' },
      Memory:       { RAM: '12 GB', ROM: '256 GB', Card: 'MicroSDXC' },
      Battery:      { Capacity: '5000 mAh', Charging: '100W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.78"', Resolution: '1080 x 2436', Extras: '144Hz' },
      Processor:    { Chipset: 'Dimensity 7300 Ultimate (4nm)', CPU: 'Octa-core', GPU: 'Mali-G615' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 6E', Bluetooth: 'v5.4', USB: 'USB Type-C', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Under display (optical)', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Compass, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers (JBL)', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 10,
    name: 'Infinix Note 50 Pro',
    price: 54999,
    image: '/mobiles/infinix-note-50-pro.png',
    brand: 'Infinix',
    priceType: 'Official',
    variants: [{ label: '8GB + 256GB', price: 54999 }],
    specs: {
      Build:        { OS: 'Android 15', UI: 'XOS 15.1', SIM: 'Dual Nano-SIM', Weight: '195 g' },
      Camera:       { Back: '108 MP + 2 MP', 'Back Video': '1080p@60fps', Front: '32 MP' },
      Memory:       { RAM: '8 GB', ROM: '256 GB', Card: 'MicroSDXC' },
      Battery:      { Capacity: '5000 mAh', Charging: '68W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.78"', Resolution: '1080 x 2436', Extras: '144Hz' },
      Processor:    { Chipset: 'Helio G100 Ultimate (6nm)', CPU: 'Octa-core', GPU: 'Mali-G57 MC5' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 a/b/g/n/ac', Bluetooth: 'v5.4', USB: 'USB Type-C', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Under display (optical)', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers (JBL)', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 11,
    name: 'Realme 12 Plus',
    price: 49999,
    image: '/mobiles/realme-12-plus.png',
    brand: 'Realme',
    priceType: 'Official',
    variants: [{ label: '8GB + 256GB', price: 49999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'Realme UI 5.0', SIM: 'Dual Nano-SIM', Weight: '185 g' },
      Camera:       { Back: '50 MP + 8 MP + 2 MP', 'Back Video': '4K@30fps', Front: '16 MP' },
      Memory:       { RAM: '8 GB', ROM: '256 GB', Card: 'No' },
      Battery:      { Capacity: '5000 mAh', Charging: '67W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.67"', Resolution: '1080 x 2412', Extras: '120Hz, 2160Hz PWM' },
      Processor:    { Chipset: 'Dimensity 7050 (6nm)', CPU: 'Octa-core', GPU: 'Mali-G68' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 6', Bluetooth: 'v5.3', USB: 'USB Type-C', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Under display (optical)', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Compass, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 12,
    name: 'Vivo Y300',
    price: 44999,
    image: '/mobiles/vivo-y300.png',
    brand: 'Vivo',
    priceType: 'Official',
    variants: [{ label: '8GB + 128GB', price: 44999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'FunTouch OS 14', SIM: 'Dual Nano-SIM', Weight: '186 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '16 MP' },
      Memory:       { RAM: '8 GB', ROM: '128 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '44W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.67"', Resolution: '1080 x 2400', Extras: '120Hz' },
      Processor:    { Chipset: 'Snapdragon 4 Gen 2 (4nm)', CPU: 'Octa-core', GPU: 'Adreno 613' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 6', Bluetooth: 'v5.4', USB: 'USB Type-C', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Under display (optical)', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 13,
    name: 'Oppo A3 Pro',
    price: 42999,
    image: '/mobiles/oppo-a3-pro.png',
    brand: 'Oppo',
    priceType: 'Official',
    variants: [{ label: '8GB + 256GB', price: 42999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'ColorOS 14', SIM: 'Dual Nano-SIM', Weight: '183 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '8 GB', ROM: '256 GB', Card: 'No' },
      Battery:      { Capacity: '5000 mAh', Charging: '45W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.7"', Resolution: '1080 x 2412', Extras: '120Hz' },
      Processor:    { Chipset: 'Dimensity 7050 (6nm)', CPU: 'Octa-core', GPU: 'Mali-G68' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 6', Bluetooth: 'v5.3', USB: 'USB Type-C', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Under display (optical)', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 14,
    name: 'Samsung Galaxy A35',
    price: 48999,
    image: '/mobiles/samsung-galaxy-a35.png',
    brand: 'Samsung',
    priceType: 'Official',
    variants: [{ label: '8GB + 128GB', price: 48999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'One UI 6.1', SIM: 'Dual Nano-SIM', Weight: '210 g', Material: 'Gorilla Glass Victus+ front, Plastic back' },
      Camera:       { Back: '50 MP + 8 MP + 5 MP', 'Back Video': '4K@30fps', Front: '13 MP' },
      Memory:       { RAM: '8 GB', ROM: '128 GB', Card: 'MicroSD (Dedicated Slot)' },
      Battery:      { Capacity: '5000 mAh', Charging: '25W Fast Charging' },
      Display:      { Technology: 'Super AMOLED', Size: '6.6"', Resolution: '1080 x 2340', Extras: '120Hz', Protection: 'Gorilla Glass Victus+' },
      Processor:    { Chipset: 'Exynos 1380 (5nm)', CPU: 'Octa-core', GPU: 'Mali-G68 MP5' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 6', Bluetooth: 'v5.3', USB: 'USB Type-C', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Under display (optical)', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Compass, Proximity, Barometer' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 15,
    name: 'Xiaomi Redmi Note 14',
    price: 45999,
    image: '/mobiles/xiaomi-redmi-note-14.png',
    brand: 'Xiaomi',
    priceType: 'Official',
    variants: [{ label: '8GB + 256GB', price: 45999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'MIUI 14', SIM: 'Dual Nano-SIM', Weight: '190 g' },
      Camera:       { Back: '108 MP + 8 MP + 2 MP', 'Back Video': '4K@30fps', Front: '20 MP' },
      Memory:       { RAM: '8 GB', ROM: '256 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5110 mAh', Charging: '33W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.67"', Resolution: '1080 x 2400', Extras: '120Hz' },
      Processor:    { Chipset: 'Snapdragon 4s Gen 2 (4nm)', CPU: 'Octa-core', GPU: 'Adreno 710' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 a/b/g/n/ac', Bluetooth: 'v5.4', USB: 'USB Type-C', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 16,
    name: 'Samsung Galaxy A16',
    price: 37999,
    image: '/mobiles/samsung-galaxy-a16.png',
    brand: 'Samsung',
    priceType: 'Official',
    variants: [{ label: '6GB + 128GB', price: 37999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'One UI 6.1', SIM: 'Dual Nano-SIM', Weight: '200 g' },
      Camera:       { Back: '50 MP + 5 MP + 2 MP', 'Back Video': '4K@30fps', Front: '13 MP' },
      Memory:       { RAM: '6 GB', ROM: '128 GB', Card: 'MicroSD (Dedicated Slot)' },
      Battery:      { Capacity: '5000 mAh', Charging: '25W Fast Charging' },
      Display:      { Technology: 'Super AMOLED', Size: '6.7"', Resolution: '1080 x 2340', Extras: '90Hz' },
      Processor:    { Chipset: 'Exynos 1330 (5nm)', CPU: 'Octa-core', GPU: 'Mali-G52 MP1' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 a/b/g/n/ac', Bluetooth: 'v5.3', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 17,
    name: 'Tecno Spark 30C',
    price: 34999,
    image: '/mobiles/tecno-spark-30c.png',
    brand: 'Tecno',
    priceType: 'Official',
    variants: [{ label: '8GB + 128GB', price: 34999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'HiOS 14', SIM: 'Dual Nano-SIM', Weight: '195 g' },
      Camera:       { Back: '50 MP + 0.08 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '8 GB', ROM: '128 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '18W Fast Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.78"', Resolution: '720 x 1612', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc T606 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G57' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 18,
    name: 'Infinix Hot 50 Pro',
    price: 32999,
    image: '/mobiles/infinix-hot-50-pro.png',
    brand: 'Infinix',
    priceType: 'Official',
    variants: [{ label: '8GB + 128GB', price: 32999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'XOS 14', SIM: 'Dual Nano-SIM', Weight: '185 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '32 MP' },
      Memory:       { RAM: '8 GB', ROM: '128 GB', Card: 'MicroSDXC' },
      Battery:      { Capacity: '5000 mAh', Charging: '33W Fast Charging' },
      Display:      { Technology: 'AMOLED', Size: '6.78"', Resolution: '1080 x 2436', Extras: '120Hz' },
      Processor:    { Chipset: 'Helio G99 (6nm)', CPU: 'Octa-core', GPU: 'Mali-G57 MC2' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 a/b/g/n/ac', Bluetooth: 'v5.4', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 19,
    name: 'Realme C65',
    price: 27999,
    image: '/mobiles/realme-c65.png',
    brand: 'Realme',
    priceType: 'Official',
    variants: [{ label: '6GB + 128GB', price: 27999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'Realme UI 5.0', SIM: 'Dual Nano-SIM', Weight: '188 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '6 GB', ROM: '128 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '33W Fast Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.67"', Resolution: '720 x 1604', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc T612 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G57' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'Micro-USB', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 20,
    name: 'Infinix Hot 50i',
    price: 24999,
    image: '/mobiles/infinix-hot-50i.png',
    brand: 'Infinix',
    priceType: 'Official',
    variants: [{ label: '4GB + 128GB', price: 24999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'XOS 14', SIM: 'Dual Nano-SIM', Weight: '190 g' },
      Camera:       { Back: '50 MP + 0.08 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '4 GB', ROM: '128 GB', Card: 'MicroSDXC' },
      Battery:      { Capacity: '5000 mAh', Charging: '18W Fast Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.6"', Resolution: '720 x 1612', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc T606 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G57' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 21,
    name: 'Tecno Spark 20C',
    price: 22999,
    image: '/mobiles/tecno-spark-20c.png',
    brand: 'Tecno',
    priceType: 'Official',
    variants: [{ label: '4GB + 64GB', price: 22999 }],
    specs: {
      Build:        { OS: 'Android 13', UI: 'HiOS 13', SIM: 'Dual Nano-SIM', Weight: '192 g' },
      Camera:       { Back: '50 MP + 0.08 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '4 GB', ROM: '64 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '18W Fast Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.56"', Resolution: '720 x 1612', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc T606 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G57' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 22,
    name: 'Samsung Galaxy A06',
    price: 25999,
    image: '/mobiles/samsung-galaxy-a06.png',
    brand: 'Samsung',
    priceType: 'Official',
    variants: [{ label: '4GB + 64GB', price: 25999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'One UI 6.1', SIM: 'Dual Nano-SIM', Weight: '195 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '4 GB', ROM: '64 GB', Card: 'MicroSD (Dedicated Slot)' },
      Battery:      { Capacity: '5000 mAh', Charging: '25W Fast Charging' },
      Display:      { Technology: 'PLS LCD', Size: '6.7"', Resolution: '720 x 1604', Extras: '90Hz' },
      Processor:    { Chipset: 'Exynos 850 (8nm)', CPU: 'Octa-core', GPU: 'Mali-G52' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 23,
    name: 'Xiaomi Redmi 14C',
    price: 28999,
    image: '/mobiles/xiaomi-redmi-14c.png',
    brand: 'Xiaomi',
    priceType: 'Official',
    variants: [{ label: '4GB + 128GB', price: 28999 }],
    specs: {
      Build:        { OS: 'Android 14', UI: 'MIUI 14', SIM: 'Dual Nano-SIM', Weight: '211 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '13 MP' },
      Memory:       { RAM: '4 GB', ROM: '128 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5160 mAh', Charging: '18W Fast Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.88"', Resolution: '720 x 1640', Extras: '120Hz' },
      Processor:    { Chipset: 'Helio G85 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G52 MC2' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.4', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 24,
    name: 'Vivo Y19s',
    price: 23999,
    image: '/mobiles/vivo-y19s.png',
    brand: 'Vivo',
    priceType: 'Official',
    variants: [{ label: '4GB + 64GB', price: 23999 }],
    specs: {
      Build:        { OS: 'Android 13', UI: 'FunTouch OS 13', SIM: 'Dual Nano-SIM', Weight: '193 g' },
      Camera:       { Back: '50 MP + 0.08 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '4 GB', ROM: '64 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '15W Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.56"', Resolution: '720 x 1612', Extras: '90Hz' },
      Processor:    { Chipset: 'Helio G85 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G52 MC2' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'Micro-USB', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 25,
    name: 'Realme C30',
    price: 17999,
    image: '/mobiles/realme-c30.png',
    brand: 'Realme',
    priceType: 'Official',
    variants: [{ label: '3GB + 32GB', price: 17999 }],
    specs: {
      Build:        { OS: 'Android 11', UI: 'Realme UI Go', SIM: 'Dual Nano-SIM', Weight: '182 g' },
      Camera:       { Back: '8 MP', 'Back Video': '1080p@30fps', Front: '5 MP' },
      Memory:       { RAM: '3 GB', ROM: '32 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '10W Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.5"', Resolution: '720 x 1600', Extras: '60Hz' },
      Processor:    { Chipset: 'Unisoc SC9863A1 (28nm)', CPU: 'Octa-core', GPU: 'PowerVR GE8322' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'Micro-USB', NFC: 'No' },
      Sensors:      { Fingerprint: 'No', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 26,
    name: 'Infinix Smart 8',
    price: 14999,
    image: '/mobiles/infinix-smart-8.png',
    brand: 'Infinix',
    priceType: 'Official',
    variants: [{ label: '3GB + 64GB', price: 14999 }],
    specs: {
      Build:        { OS: 'Android 13 Go', UI: 'XOS 13', SIM: 'Dual Nano-SIM', Weight: '192 g' },
      Camera:       { Back: '13 MP + 0.08 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '3 GB', ROM: '64 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '10W Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.6"', Resolution: '720 x 1612', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc T606 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G57' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 27,
    name: 'Tecno Pop 8',
    price: 12999,
    image: '/mobiles/tecno-pop-8.png',
    brand: 'Tecno',
    priceType: 'Official',
    variants: [{ label: '2GB + 64GB', price: 12999 }],
    specs: {
      Build:        { OS: 'Android 13 Go', UI: 'HiOS 13', SIM: 'Dual Nano-SIM', Weight: '180 g' },
      Camera:       { Back: '8 MP', 'Back Video': '1080p@30fps', Front: '5 MP' },
      Memory:       { RAM: '2 GB', ROM: '64 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '10W Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.6"', Resolution: '720 x 1612', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc T606 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G57' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'No', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 28,
    name: 'Nokia C32',
    price: 16999,
    image: '/mobiles/nokia-c32.png',
    brand: 'Nokia',
    priceType: 'Official',
    variants: [{ label: '3GB + 64GB', price: 16999 }],
    specs: {
      Build:        { OS: 'Android 13', UI: 'Stock Android', SIM: 'Dual Nano-SIM', Weight: '197 g', Material: 'Polycarbonate back' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '8 MP' },
      Memory:       { RAM: '3 GB', ROM: '64 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '10W Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.52"', Resolution: '720 x 1600', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc T606 (12nm)', CPU: 'Octa-core', GPU: 'Mali-G57' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 29,
    name: 'Itel A70',
    price: 10999,
    image: '/mobiles/itel-a70.png',
    brand: 'Itel',
    priceType: 'Official',
    variants: [{ label: '3GB + 64GB', price: 10999 }],
    specs: {
      Build:        { OS: 'Android 13 Go', UI: 'itelOS 13', SIM: 'Dual Nano-SIM', Weight: '175 g' },
      Camera:       { Back: '8 MP', 'Back Video': '720p@30fps', Front: '5 MP' },
      Memory:       { RAM: '3 GB', ROM: '64 GB', Card: 'MicroSD' },
      Battery:      { Capacity: '5000 mAh', Charging: '10W Charging' },
      Display:      { Technology: 'IPS LCD', Size: '6.6"', Resolution: '720 x 1612', Extras: '90Hz' },
      Processor:    { Chipset: 'Unisoc SC9863A (28nm)', CPU: 'Octa-core', GPU: 'PowerVR GE8322' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'No', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },
  {
    id: 30,
    name: 'Samsung Galaxy A05',
    price: 18999,
    image: '/mobiles/samsung-galaxy-a05.png',
    brand: 'Samsung',
    priceType: 'Official',
    variants: [{ label: '4GB + 64GB', price: 18999 }],
    specs: {
      Build:        { OS: 'Android 13', UI: 'One UI 5.1', SIM: 'Dual Nano-SIM', Weight: '195 g' },
      Camera:       { Back: '50 MP + 2 MP', 'Back Video': '1080p@30fps', Front: '13 MP' },
      Memory:       { RAM: '4 GB', ROM: '64 GB', Card: 'MicroSD (Dedicated Slot)' },
      Battery:      { Capacity: '5000 mAh', Charging: '25W Fast Charging' },
      Display:      { Technology: 'PLS LCD', Size: '6.7"', Resolution: '720 x 1604', Extras: '60Hz' },
      Processor:    { Chipset: 'Snapdragon 680 (6nm)', CPU: 'Octa-core', GPU: 'Adreno 610' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'No' },
      Connectivity: { WLAN: 'Wi-Fi 802.11 b/g/n', Bluetooth: 'v5.0', USB: 'USB Type-C', NFC: 'No' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Yes', 'Other Sensors': 'Accelerometer, Proximity' },
      Sound:        { Speaker: 'Mono Speaker', '3.5mm Jack': 'Yes' },
    },
  },

  // ── APPLE ──────────────────────────────────────────────────
  {
    id: 31,
    name: 'Apple iPhone 16 Pro Max',
    price: 549999,
    image: '/mobiles/iphone-16-pro-max.png',
    brand: 'Apple',
    priceType: 'Exp',
    variants: [{ label: '256GB', price: 549999 }, { label: '512GB', price: 619999 }, { label: '1TB', price: 699999 }],
    specs: {
      Build:        { OS: 'iOS 18', Weight: '227 g', SIM: 'Nano + eSIM', Colors: 'Black, White, Natural, Desert Titanium', Material: 'Titanium Frame, Textured Matte Glass back' },
      Camera:       { Back: '48 MP + 48 MP + 12 MP', 'Back Features': 'OIS, 5x Optical Zoom, Night Mode', 'Back Video': '4K@120fps', Front: '12 MP', 'Front Features': '4K Video, Autofocus' },
      Memory:       { RAM: '8 GB', ROM: '256 GB / 512 GB / 1 TB', Card: 'No' },
      Battery:      { Capacity: '4685 mAh', Type: 'Li-Ion', Charging: '25W MagSafe, 15W Qi2' },
      Display:      { Size: '6.9"', Resolution: '1329 x 2868', Technology: 'LTPO OLED', 'Refresh Rate': '120Hz', Extras: 'Dolby Vision, Always-On', Protection: 'Ceramic Shield' },
      Processor:    { Chipset: 'Apple A18 Pro (3nm)', CPU: 'Hexa Core', GPU: 'Apple GPU (6-core)' },
      Network:      { '2G': 'Yes', '3G': 'Yes', '4G': 'Yes', '5G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 7', Bluetooth: 'v5.3', USB: 'USB-C 3.2', NFC: 'Yes', GPS: 'Yes + A-GPS, GLONASS' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Face ID', 'Other Sensors': 'Accelerometer, Gyro, Barometer, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 32,
    name: 'Apple iPhone 16 Pro',
    price: 469999,
    image: '/mobiles/iphone-16-pro.png',
    brand: 'Apple',
    priceType: 'Exp',
    variants: [{ label: '128GB', price: 469999 }, { label: '256GB', price: 519999 }, { label: '512GB', price: 599999 }],
    specs: {
      Build:        { OS: 'iOS 18', Weight: '199 g', SIM: 'Nano + eSIM', Material: 'Titanium Frame' },
      Camera:       { Back: '48 MP + 48 MP + 12 MP', 'Back Video': '4K@120fps', Front: '12 MP' },
      Memory:       { RAM: '8 GB', ROM: '128 GB / 256 GB / 512 GB / 1 TB', Card: 'No' },
      Battery:      { Capacity: '3274 mAh', Charging: '27W Wired, 25W MagSafe' },
      Display:      { Size: '6.3"', Resolution: '1206 x 2622', Technology: 'LTPO OLED', 'Refresh Rate': '120Hz', Protection: 'Ceramic Shield' },
      Processor:    { Chipset: 'Apple A18 Pro (3nm)', CPU: 'Hexa Core', GPU: 'Apple GPU (6-core)' },
      Network:      { '5G': 'Yes', '4G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 7', Bluetooth: 'v5.3', USB: 'USB-C 3.2', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Face ID', 'Other Sensors': 'Accelerometer, Gyro, Barometer' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 33,
    name: 'Apple iPhone 16',
    price: 359999,
    image: '/mobiles/iphone-16.png',
    brand: 'Apple',
    priceType: 'Exp',
    variants: [{ label: '128GB', price: 359999 }, { label: '256GB', price: 409999 }],
    specs: {
      Build:        { OS: 'iOS 18', Weight: '170 g', SIM: 'Nano + eSIM', Material: 'Aluminum Frame, Glass back' },
      Camera:       { Back: '48 MP + 12 MP', 'Back Video': '4K@60fps', Front: '12 MP' },
      Memory:       { RAM: '8 GB', ROM: '128 GB / 256 GB / 512 GB', Card: 'No' },
      Battery:      { Capacity: '3561 mAh', Charging: '20W Wired, 25W MagSafe' },
      Display:      { Size: '6.1"', Resolution: '1179 x 2556', Technology: 'Super Retina XDR OLED', 'Refresh Rate': '60Hz', Protection: 'Ceramic Shield' },
      Processor:    { Chipset: 'Apple A18 (3nm)', CPU: 'Hexa Core', GPU: 'Apple GPU (5-core)' },
      Network:      { '5G': 'Yes', '4G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 6E', Bluetooth: 'v5.3', USB: 'USB-C 2.0', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Face ID', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 34,
    name: 'Apple iPhone 15 Pro Max',
    price: 499999,
    image: '/mobiles/iphone-15-pro-max.png',
    brand: 'Apple',
    priceType: 'Exp',
    variants: [{ label: '256GB', price: 499999 }, { label: '512GB', price: 569999 }],
    specs: {
      Build:        { OS: 'iOS 17', Weight: '221 g', SIM: 'Nano + eSIM', Material: 'Titanium Frame' },
      Camera:       { Back: '48 MP + 12 MP + 12 MP', 'Back Video': '4K@60fps', Front: '12 MP' },
      Memory:       { RAM: '8 GB', ROM: '256 GB / 512 GB / 1 TB', Card: 'No' },
      Battery:      { Capacity: '4422 mAh', Charging: '27W Wired, 15W MagSafe' },
      Display:      { Size: '6.7"', Resolution: '1290 x 2796', Technology: 'LTPO OLED', 'Refresh Rate': '120Hz', Protection: 'Ceramic Shield' },
      Processor:    { Chipset: 'Apple A17 Pro (3nm)', CPU: 'Hexa Core', GPU: 'Apple GPU (6-core)' },
      Network:      { '5G': 'Yes', '4G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 6E', Bluetooth: 'v5.3', USB: 'USB-C 3.2', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Face ID', 'Other Sensors': 'Accelerometer, Gyro, Barometer' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
  {
    id: 35,
    name: 'Apple iPhone 15',
    price: 319999,
    image: '/mobiles/iphone-15.png',
    brand: 'Apple',
    priceType: 'Exp',
    variants: [{ label: '128GB', price: 319999 }, { label: '256GB', price: 369999 }],
    specs: {
      Build:        { OS: 'iOS 17', Weight: '171 g', SIM: 'Nano + eSIM', Material: 'Aluminum Frame, Glass back' },
      Camera:       { Back: '48 MP + 12 MP', 'Back Video': '4K@60fps', Front: '12 MP' },
      Memory:       { RAM: '6 GB', ROM: '128 GB / 256 GB / 512 GB', Card: 'No' },
      Battery:      { Capacity: '3349 mAh', Charging: '20W, 15W MagSafe' },
      Display:      { Size: '6.1"', Resolution: '1179 x 2556', Technology: 'Super Retina XDR OLED', 'Refresh Rate': '60Hz', Protection: 'Ceramic Shield' },
      Processor:    { Chipset: 'Apple A16 Bionic (4nm)', CPU: 'Hexa Core', GPU: 'Apple GPU (5-core)' },
      Network:      { '5G': 'Yes', '4G': 'Yes' },
      Connectivity: { WLAN: 'Wi-Fi 6', Bluetooth: 'v5.3', USB: 'USB-C 2.0', NFC: 'Yes' },
      Sensors:      { Fingerprint: 'Side-mounted', 'Face Unlock': 'Face ID', 'Other Sensors': 'Accelerometer, Gyro, Proximity' },
      Sound:        { Speaker: 'Stereo Speakers', '3.5mm Jack': 'No' },
    },
  },
];

// ── HELPER FUNCTIONS ─────────────────────────────────────────
export function getPhoneById(id: number): Phone | undefined {
  return ALL_PHONES.find((p) => p.id === id);
}

export function getPhonesByBrand(brand: string): Phone[] {
  return ALL_PHONES.filter((p) => p.brand.toLowerCase() === brand.toLowerCase());
}

export function getPhonesByPriceRange(min?: number, max?: number): Phone[] {
  return ALL_PHONES.filter((p) => {
    if (min !== undefined && max !== undefined) return p.price >= min && p.price <= max;
    if (min !== undefined) return p.price >= min;
    if (max !== undefined) return p.price <= max;
    return true;
  });
}

// ── HOME PAGE EXPORTS ────────────────────────────────────────
export const latestMobiles   = [...ALL_PHONES].sort((a, b) => b.id - a.id).slice(0, 10);
export const above50kMobiles = getPhonesByPriceRange(50000);
export const between40to50k  = getPhonesByPriceRange(40000, 49999);
export const between30to40k  = getPhonesByPriceRange(30000, 39999);
export const between20to30k  = getPhonesByPriceRange(20000, 29999);
export const between10to20k  = getPhonesByPriceRange(10000, 19999);

// ── Backward compatibility ───────────────────────────────────
export type Mobile = Phone;
export const allMobiles = ALL_PHONES;
export const getMobilesByBrand = getPhonesByBrand;
export const getMobilesByPriceRange = getPhonesByPriceRange;